"""init three-layer schema

Revision ID: 22ed190e93cf
Revises: 
Create Date: 2026-05-22 02:12:14.927346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ed190e93cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('creators', sa.JSON(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('container_title', sa.Text(), nullable=True),
    sa.Column('volume', sa.String(length=32), nullable=True),
    sa.Column('issue', sa.String(length=32), nullable=True),
    sa.Column('pages', sa.String(length=64), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('csl_json', sa.JSON(), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', 'owner_id', name='uq_paper_dedup')
    )
    op.create_index(op.f('ix_paper_dedup_key'), 'paper', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_paper_doi'), 'paper', ['doi'], unique=False)
    op.create_index(op.f('ix_paper_owner_id'), 'paper', ['owner_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_owner_id'), 'project', ['owner_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('messages_snapshot', sa.JSON(), nullable=True),
    sa.Column('rounds_log', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_project_id'), 'agent_run', ['project_id'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=80), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('mineru_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=True),
    sa.Column('dbsource', sa.String(length=20), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('r_corpus_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'content_hash', name='uq_corpus_hash')
    )
    op.create_index(op.f('ix_corpus_content_hash'), 'corpus', ['content_hash'], unique=False)
    op.create_index(op.f('ix_corpus_project_id'), 'corpus', ['project_id'], unique=False)
    op.create_table('draft',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_project_id'), 'draft', ['project_id'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_tag',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'tag_id')
    )
    op.create_table('project_paper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('inclusion_status', sa.String(length=16), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('screening_score', sa.Integer(), nullable=True),
    sa.Column('screening_notes', sa.Text(), nullable=True),
    sa.Column('added_by', sa.String(length=8), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'paper_id', name='uq_project_paper')
    )
    op.create_index(op.f('ix_project_paper_paper_id'), 'project_paper', ['paper_id'], unique=False)
    op.create_index(op.f('ix_project_paper_project_id'), 'project_paper', ['project_id'], unique=False)
    op.create_table('corpus_paper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('inclusion_status_snapshot', sa.String(length=16), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('csl_json_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_paper_corpus_id'), 'corpus_paper', ['corpus_id'], unique=False)
    op.create_index(op.f('ix_corpus_paper_paper_id'), 'corpus_paper', ['paper_id'], unique=False)
    # C2: corpus_paper 唯一约束，防止同 corpus 重复写入同一 paper
    op.create_unique_constraint('uq_corpus_paper', 'corpus_paper', ['corpus_id', 'paper_id'])
    # C1: paper.owner_id IS NULL 时的部分唯一索引（PostgreSQL NULL≠NULL，普通复合约束不强制）
    op.create_index(
        'uq_paper_dedup_null_owner',
        'paper',
        ['dedup_key'],
        unique=True,
        postgresql_where=sa.text('owner_id IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corpus_paper_paper_id'), table_name='corpus_paper')
    op.drop_index('uq_paper_dedup_null_owner', table_name='paper')
    op.drop_constraint('uq_corpus_paper', 'corpus_paper', type_='unique')
    op.drop_index(op.f('ix_corpus_paper_corpus_id'), table_name='corpus_paper')
    op.drop_table('corpus_paper')
    op.drop_index(op.f('ix_project_paper_project_id'), table_name='project_paper')
    op.drop_index(op.f('ix_project_paper_paper_id'), table_name='project_paper')
    op.drop_table('project_paper')
    op.drop_table('paper_tag')
    op.drop_table('note')
    op.drop_index(op.f('ix_draft_project_id'), table_name='draft')
    op.drop_table('draft')
    op.drop_index(op.f('ix_corpus_project_id'), table_name='corpus')
    op.drop_index(op.f('ix_corpus_content_hash'), table_name='corpus')
    op.drop_table('corpus')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_agent_run_project_id'), table_name='agent_run')
    op.drop_table('agent_run')
    op.drop_table('tag')
    op.drop_index(op.f('ix_project_owner_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_paper_owner_id'), table_name='paper')
    op.drop_index(op.f('ix_paper_doi'), table_name='paper')
    op.drop_index(op.f('ix_paper_dedup_key'), table_name='paper')
    op.drop_table('paper')
    # ### end Alembic commands ###
