"""m2 event hash chain + validation_summary + project name unique

Revision ID: 320f5900dda6
Revises: d7b1f517dc88
Create Date: 2026-05-22 22:22:19.224149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320f5900dda6'
down_revision: Union[str, Sequence[str], None] = 'd7b1f517dc88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    M2: agent_event 哈希链(prev_hash/event_hash 均 nullable，既有行保持 NULL=legacy) +
    agent_run.validation_summary + project.name 唯一约束(codex P0，使 project__create 幂等)。
    注：若目标库已存在重名 project，create_unique_constraint 会失败——需先去重再迁移；
    测试库由 fixture 全新建库，不受影响。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_event', sa.Column('prev_hash', sa.String(length=64), nullable=True))
    op.add_column('agent_event', sa.Column('event_hash', sa.String(length=64), nullable=True))
    op.add_column('agent_run', sa.Column('validation_summary', sa.JSON(), nullable=True))
    op.create_unique_constraint('uq_project_name', 'project', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_name', 'project', type_='unique')
    op.drop_column('agent_run', 'validation_summary')
    op.drop_column('agent_event', 'event_hash')
    op.drop_column('agent_event', 'prev_hash')
    # ### end Alembic commands ###
