"""add_attachment_markdown_path

Revision ID: 968a241462c2
Revises: 22ed190e93cf
Create Date: 2026-05-22 09:58:59.100285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968a241462c2'
down_revision: Union[str, Sequence[str], None] = '22ed190e93cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('markdown_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'markdown_path')
    # ### end Alembic commands ###
