"""agent runtime: agent_run cols + agent_event + tool_invocation

Revision ID: d7b1f517dc88
Revises: 968a241462c2
Create Date: 2026-05-22 20:21:41.201065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b1f517dc88'
down_revision: Union[str, Sequence[str], None] = '968a241462c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq', name='uq_agent_event_seq')
    )
    op.create_index(op.f('ix_agent_event_run_id'), 'agent_event', ['run_id'], unique=False)
    op.create_table('tool_invocation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('tool_id', sa.String(length=40), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'idempotency_key', name='uq_tool_invocation_key')
    )
    op.create_index(op.f('ix_tool_invocation_run_id'), 'tool_invocation', ['run_id'], unique=False)
    op.add_column('agent_run', sa.Column('cursor', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('agent_run', sa.Column('auto_confirm', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('agent_run', sa.Column('final_output', sa.Text(), nullable=True))
    op.add_column('agent_run', sa.Column('evidence_refs', sa.JSON(), nullable=True))
    op.add_column('agent_run', sa.Column('pending_round', sa.JSON(), nullable=True))
    op.alter_column('agent_run', 'status',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=24),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_run', 'status',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    op.drop_column('agent_run', 'pending_round')
    op.drop_column('agent_run', 'evidence_refs')
    op.drop_column('agent_run', 'final_output')
    op.drop_column('agent_run', 'auto_confirm')
    op.drop_column('agent_run', 'cursor')
    op.drop_index(op.f('ix_tool_invocation_run_id'), table_name='tool_invocation')
    op.drop_table('tool_invocation')
    op.drop_index(op.f('ix_agent_event_run_id'), table_name='agent_event')
    op.drop_table('agent_event')
    # ### end Alembic commands ###
