"""add document_structure

Revision ID: eb2f7c71c456
Revises: b8a9f0d1c2e3
Create Date: 2026-06-14 20:37:10.786394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2f7c71c456'
down_revision: Union[str, Sequence[str], None] = 'b8a9f0d1c2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.Column('content_list', sa.JSON(), nullable=True),
    sa.Column('page_map', sa.JSON(), nullable=True),
    sa.Column('block_line_ranges', sa.JSON(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('has_bbox', sa.Boolean(), nullable=False),
    sa.Column('markdown_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('bbox_coord_space', sa.String(length=20), nullable=True),
    sa.Column('page_width', sa.Float(), nullable=True),
    sa.Column('page_height', sa.Float(), nullable=True),
    sa.Column('rotation', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_structure_attachment_id'), 'document_structure', ['attachment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_structure_attachment_id'), table_name='document_structure')
    op.drop_table('document_structure')
    # ### end Alembic commands ###
